pipeline {
    agent any

    tools {
        maven 'maven'
    }

    stages {

        stage('Build') {
            steps {
                dir('sak_spring_EC2_mysql_RDS-main') {
                    sh 'mvn clean package'
                }
            }
            post {
                success {
                    echo 'Build Success'
                }
                failure {
                    echo 'Build Failure'
                }
            }
        }

        stage('Test') {
            steps {
                dir('sak_spring_EC2_mysql_RDS-main') {
                    sh 'mvn test'
                }
            }
            post {
                success {
                    echo 'Test Success'
                }
                failure {
                    echo 'Test Failure'
                }
            }
        }

        stage('Run Spring Boot Application') {
            steps {
                dir('sak_spring_EC2_mysql_RDS-main') {
                    sh '''
                    echo "Stopping existing application..."
                    sudo pkill -f spring_app_sak-0.0.1-SNAPSHOT.jar || true

                    echo "Starting application..."
                    sudo nohup java -jar target/spring_app_sak-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
                    '''
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline Success'
        }
        failure {
            echo 'Pipeline Failure'
        }
    }
}